title: "Tactile Board"
description: "Documentation for the Tactile Board Android Application"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
permalink: pretty

exclude: [ "README.md" ]

footer_content: "Copyright &copy; 2021 Affective & Cognitive Institute. Distributed by an <a href=\"https://github.com/Suitceyes-Project-Code/Tactile-Board-Listener/blob/master/LICENSE\">MIT license.</a>"
logo: "/assets/images/suitceyes.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search.heading_level: 1